

# 📂 GitHub to Google Drive Sync – Complete Guide

This guide explains how to set up an automated backup from GitHub to a **Google Workspace Shared Drive**.
**Setup Effort:** Once per Google Account.
**Reusability:** Unlimited repositories.

---

## ✅ Phase 1: Google Cloud (One-Time)

*You only need to do this once. The resulting Key works for all your projects.*

1. Go to **[Google Cloud Console](https://console.cloud.google.com/)**.
2. Create a **New Project** (e.g., `github-backup-bot`).
3. Search for **"Google Drive API"** and **enable** it.
4. Go to **IAM & Admin > Service Accounts** -> **Create Service Account**.
5. Click on the new account -> **Keys** -> **Add Key** -> **Create new key** -> **JSON**.
6. **Save the JSON file**. You will need its content later.
7. Copy the **Service Account Email** (e.g., `github-uploader@...`).

---

## ✅ Phase 2: Google Drive (Shared Drive)

*REQUIRED: You must use a "Shared Drive" (Workspace), not "My Drive", to avoid quota errors.*

1. Go to Google Drive -> **Shared Drives**.
2. Create a new Shared Drive (or open an existing one).
3. **Manage Members** -> Add the **Service Account Email**.
4. **Role:** Set to **Content Manager** (Essential!).
5. Create/Open the target folder for your repo.
6. **Copy the Folder ID** from the browser URL (the string after `/folders/...`).

---

## ✅ Phase 3: GitHub Secrets

Go to your Repository -> **Settings** -> **Secrets and variables** -> **Actions** -> **New repository secret**.

| Secret Name | Value |
| --- | --- |
| `GCP_SA_KEY` | Paste the **entire content** of the JSON Key file here. |
| `DRIVE_FOLDER_ID` | Paste the **Folder ID** from Phase 2. |

---

## ✅ Phase 4: The Workflow Script

Create a file at `.github/workflows/google-drive-sync.yml` and paste this code:

```yaml
name: Sync to Google Drive (Workspace)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM
  workflow_dispatch:    # Allows manual trigger

jobs:
  backup-to-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Sync to Google Drive
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        run: |
          # 1. Create service account key file from secret
          echo "$GCP_SA_KEY" > sa_key.json

          # 2. Configure Rclone via environment variables (On-the-fly config)
          export RCLONE_CONFIG_GDRIVE_TYPE=drive
          export RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE=sa_key.json
          
          # IMPORTANT: Disable trash for Shared Drives to prevent errors and storage clutter
          export RCLONE_DRIVE_USE_TRASH=false

          # 3. Run Sync
          # - Using 'gdrive' remote defined above
          # - Excludes huge dependencies (.git, node_modules) to save time/bandwidth
          rclone sync . gdrive: \
            --drive-root-folder-id "$DRIVE_FOLDER_ID" \
            --exclude "node_modules/**" \
            --exclude ".git/**" \
            --exclude "sa_key.json" \
            --exclude "dist/**" \
            --progress

          # 4. Security Cleanup
          rm sa_key.json

```
